name: Multi-Job Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      run_test:
        required: false
        type: boolean
        default: true
      run_upload:
        required: false
        type: boolean
        default: false

jobs:
  test:
    if: ${{ inputs.run_test }}
    runs-on: ubuntu-latest
    outputs:
      summary: ${{ steps.set-summary.outputs.result }}
    steps:
      - name: Run tests
        run: echo "Running tests for ${{ inputs.environment }}"
      - name: Set test result summary
        id: set-summary
        run: echo "result=Tests passed on ${{ inputs.environment }}" >> $GITHUB_OUTPUT

  upload-results:
    if: ${{ inputs.run_upload }}
    outputs:
      upload: ${{ steps.set-upload.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        run: echo "Uploading results for ${{ inputs.environment }}"
      - name: Set test result upload
        id: set-upload
        run: echo "result=Tests passed on ${{ inputs.environment }}" >> $GITHUB_OUTPUT
